[package]
name = "DeviceParamsPost"
version = "0.1.0"
edition = "2024"

[dependencies]
mysql = "20.0"
redis = "0.23"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
calamine = "0.21"
chrono = "0.4"
